name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    name: RuboCop Linting
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0 # Ruby version
          bundler-cache: true # Caches dependencies for faster builds

      # Install dependencies
      - name: Install Gems
        run: bundle install

      # Run RuboCop
      - name: Run RuboCop
        run: bundle exec rubocop

  tests:
    name: Rails Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0 # Ruby version
          bundler-cache: true # Caches dependencies for faster builds

      # Install dependencies
      - name: Install Gems
        run: bundle install

      # Run Rails Tests
      - name: Run Rails Tests
        env:
          RAILS_ENV: test
        run: bundle exec rails test
